### ISSUE TITLE
出错了

### ISSUE THREAD

**Issue by disburden** [luyongfugx/flutter_ocr#1]
具体哪里报错还不清楚,打了一堆日志发现在这一句后面日志就不打了
ImageUtil.Image uImage = await sendReceive(sendPort, pngBytes);
错误的内容好像是网络请求的.估计调用百度api的时候出错了
DioError [DioErrorType.RESPONSE]: Http status error [400]

能帮忙看看吗?

**Comment by luyongfugx** [comment]
DioError [DioErrorType.RESPONSE]: Http status error [400]    400错误了 申请了百度api的权限了吗

**Comment by luyongfugx** [comment]
image_page.dart：
`        String baiduApi = "https://aip.baidubce.com/oauth/2.0/token?";	
	String baiduRestApi = "https://aip.baidubce.com/rest/2.0/ocr/v1/general_basic?";
	String baiduGrantType = "client_credentials";
	String baiduClientId = "";//百度ocr api的 clientId,请自行申请
	String baiduClientSecret = "";//百度ocr api的 Secret`

这里

**Comment by disburden** [comment]
哦,明白了
我还以为你都设置好了

tks!
pls close
